---
Name: betamask
Before: adminthemes
---

SilverStripe\Admin\LeftAndMain:
  extensions:
    - SilverStripe\Betamask\Extension\LeftAndMain
  admin_themes:
    - 'silverstripeltd/betamask:/templates'
